module.exports = {
  mySidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      items: [{
        type:'autogenerated',
        dirName: 'Getting-Started',
      }]
        
    },
    {
      type: 'category',
      label: 'Development',
      collapsed: false,
      collapsible: true,
      items: [{
        type: 'autogenerated',
        dirName: 'App-Docs'
      }]
    }
  ],
};