/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  Main: [
    {
      type: 'category', 
      label: 'Getting Started',
      items: ['intro','contributing','Create-Delete-Pages'],
      collapsible: false,
    },
    {
      type: 'category',
      label: 'Documentation',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName:'documentation',
        }
      ]
    },
    {
      type: 'category',
      label: 'Team Guides',
      collapsible: false,
      items:[
        {
          type: 'category',
          label: '📹 Analysis',
          items:[
            {type:'autogenerated',dirName:'teams/analysis'}
          ]
        },
        {
          type: 'category',
          label: '🖥️ FrontEnd',
          items:[
            {type:'autogenerated',dirName:'teams/frontend'}
          ]
        },
        {
          type: 'category',
          label: '📌 Infrastructure',
          items:[
            {type:'autogenerated',dirName:'teams/infrastructure'}
          ]
        },

      ]

    }
  ],
};

module.exports = sidebars;
